- schedule:
    url: "https://fightinghawks.com/services/schedule_txt.ashx?schedule=1477"
    filepath: "./schedule.txt"
- messaging:
    server: http://192.168.1.70:555/Pi5Alerts
    token: tk_6a1yegh2fyp3fr415us7c72haufjb
- logging:
    filepath: "./log/und_fan_alert.log"